export const SET_RECIPES = "SET_RECIPES";
export const SET_CURRENT_RECIPE = "SET_CURRENT_RECIPE";
export const CLEAR_CURRENT_RECIPE = "CLEAR_CURRENT_RECIPE";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
